name: Close Issues

on:
  push:
    branches:
      - main

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          npm install @actions/github typescript @types/node --save-dev

      - name: Compile TypeScript
        run: npx tsc

      - name: Close referenced issues
        run: node dist/close-issues.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
